### ISSUE TITLE
Error im getting.

### ISSUE THREAD

**Issue by uGamers** [rumblefrog/source-chat-relay#29]
Im using the AMXX Version but I know you made this bot so im hoping you seen or know about this error.....

I removed some personal info from it but you will see the error.

fatal error: concurrent map writes

`[36mINFO[0m[0000] Server is now running on version v2.1.0-0-g64768d4. Press CTRL-C to exit. 
[36mINFO[0m[0000] Entities cache initialized                    [36mlength[0m=2
[36mINFO[0m[0000] Bot is now running                            [36mGuild Count[0m=1 [36mUsername[0m=""
[36mINFO[0m[0008] A client connected                            [36maddress[0m="127.0.0.1:56468"
[36mINFO[0m[0008] Client authenticated                          [36maddress[0m="127.0.0.1:56468" [36mhostname[0m=Half-Life [36mid[0m=""
[36mINFO[0m[2729] A client connected                            [36maddress[0m=""
[36mINFO[0m[2729] Client authenticated                          [36maddress[0m="" [36mhostname[0m="" [36mid[0m=""
[36mINFO[0m[5443] A client connected                            [36maddress[0m=""
[36mINFO[0m[5443] Client authenticated                          [36maddress[0m="" [36mhostname[0m="" [36mid[0m=""
[36mINFO[0m[8157] A client connected                            [36maddress[0m=""
[36mINFO[0m[8157] Client authenticated                          [36maddress[0m="" [36mhostname[0m="" [36mid[0m=""
[36mINFO[0m[10873] A client connected                            [36maddress[0m=""
[36mINFO[0m[10873] Client authenticated                          [36maddress[0m="" [36mhostname[0m="" [36mid[0m=""
[36mINFO[0m[13589] A client connected                            [36maddress[0m=""
[36mINFO[0m[13589] Client authenticated                          [36maddress[0m="" [36mhostname[0m="" [36mid[0m=""
[36mINFO[0m[16308] A client connected                            [36maddress[0m=""
[36mINFO[0m[16308] Client authenticated                          [36maddress[0m="" [36mhostname[0m="" [36mid[0m=""
[36mINFO[0m[19012] A client connected                            [36maddress[0m=""
[36mINFO[0m[19012] Client authenticated                          [36maddress[0m="" [36mhostname[0m="" [36mid[0m=""
[36mINFO[0m[21716] A client connected                            [36maddress[0m=""
[36mINFO[0m[21716] Client authenticated                          [36maddress[0m="" [36mhostname[0m="" [36mid[0m=""
[36mINFO[0m[24420] A client connected                            [36maddress[0m=""
[36mINFO[0m[24420] Client authenticated                          [36maddress[0m="" [36mhostname[0m="" [36mid[0m=""
fatal error: concurrent map writes

goroutine 4590 [running]:
runtime.throw(0x9cc6df, 0x15)
	/home/travis/.gimme/versions/go1.12.10.linux.amd64/src/runtime/panic.go:617 +0x72 fp=0xc000564f38 sp=0xc000564f08 pc=0x42c012
runtime.mapdelete_fast64(0x9162a0, 0xc000170270, 0xc000583c80)
	/home/travis/.gimme/versions/go1.12.10.linux.amd64/src/runtime/map_fast64.go:281 +0x328 fp=0xc000564f80 sp=0xc000564f38 pc=0x411838
github.com/rumblefrog/source-chat-relay/server/relay.(*Relay).RemoveClient(...)
	/home/travis/gopath/src/github.com/rumblefrog/source-chat-relay/server/relay/relay.go:273
github.com/rumblefrog/source-chat-relay/server/relay.(*Relay).ListenClientReceive(0xc000180140, 0xc000583c80)
	/home/travis/gopath/src/github.com/rumblefrog/source-chat-relay/server/relay/relay.go:141 +0x15d fp=0xc000564fd0 sp=0xc000564f80 pc=0x822fad
runtime.goexit()
	/home/travis/.gimme/versions/go1.12.10.linux.amd64/src/runtime/asm_amd64.s:1337 +0x1 fp=0xc000564fd8 sp=0xc000564fd0 pc=0x458691
created by github.com/rumblefrog/source-chat-relay/server/relay.(*Relay).ProcessConnections
	/home/travis/gopath/src/github.com/rumblefrog/source-chat-relay/server/relay/relay.go:129 +0x88

goroutine 1 [chan receive, 429 minutes]:
github.com/kardianos/service.(*systemd).Run.func1()
	/home/travis/gopath/src/github.com/kardianos/service/service_systemd_linux.go:212 +0xbd
github.com/kardianos/service.(*systemd).Run(0xc000116a50, 0xa7cf40, 0xe568e0)
	/home/travis/gopath/src/github.com/kardianos/service/service_systemd_linux.go:213 +0xbf
main.main()
	/home/travis/gopath/src/github.com/rumblefrog/source-chat-relay/server/main.go:104 +0x132

goroutine 5 [syscall, 429 minutes]:
os/signal.signal_recv(0x0)
	/home/travis/.gimme/versions/go1.12.10.linux.amd64/src/runtime/sigqueue.go:139 +0x9c
os/signal.loop()
	/home/travis/.gimme/versions/go1.12.10.linux.amd64/src/os/signal/signal_unix.go:23 +0x22
created by os/signal.init.0
	/home/travis/.gimme/versions/go1.12.10.linux.amd64/src/os/signal/signal_unix.go:29 +0x41

goroutine 6 [select, 429 minutes]:
database/sql.(*DB).connectionOpener(0xc0000fc240, 0xa84a40, 0xc00002aa80)
	/home/travis/.gimme/versions/go1.12.10.linux.amd64/src/database/sql/sql.go:1000 +0xe8
created by database/sql.OpenDB
	/home/travis/.gimme/versions/go1.12.10.linux.amd64/src/database/sql/sql.go:670 +0x15e

goroutine 7 [select]:
database/sql.(*DB).connectionResetter(0xc0000fc240, 0xa84a40, 0xc00002aa80)
	/home/travis/.gimme/versions/go1.12.10.linux.amd64/src/database/sql/sql.go:1013 +0xfb
created by database/sql.OpenDB
	/home/travis/.gimme/versions/go1.12.10.linux.amd64/src/database/sql/sql.go:671 +0x194

goroutine 33 [select, 429 minutes]:
github.com/go-sql-driver/mysql.(*mysqlConn).startWatcher.func1(0xc0001300c0, 0xc000124120, 0xc00012a060)
	/home/travis/gopath/src/github.com/go-sql-driver/mysql/connection.go:619 +0xbf
created by github.com/go-sql-driver/mysql.(*mysqlConn).startWatcher
	/home/travis/gopath/src/github.com/go-sql-driver/mysql/connection.go:616 +0xbe

goroutine 18 [chan receive, 2 minutes]:
github.com/rumblefrog/source-chat-relay/server/relay.(*Relay).StartRouting(0xc000180140)
	/home/travis/gopath/src/github.com/rumblefrog/source-chat-relay/server/relay/relay.go:75 +0x76
created by github.com/rumblefrog/source-chat-relay/server/relay.(*Relay).Listen
	/home/travis/gopath/src/github.com/rumblefrog/source-chat-relay/server/relay/relay.go:62 +0x148

goroutine 19 [IO wait, 22 minutes]:
internal/poll.runtime_pollWait(0x7f5940e8df38, 0x72, 0x0)
	/home/travis/.gimme/versions/go1.12.10.linux.amd64/src/runtime/netpoll.go:182 +0x56
internal/poll.(*pollDesc).wait(0xc000190198, 0x72, 0x0, 0x0, 0x9c2daf)
	/home/travis/.gimme/versions/go1.12.10.linux.amd64/src/internal/poll/fd_poll_runtime.go:87 +0x9b
internal/poll.(*pollDesc).waitRead(...)
	/home/travis/.gimme/versions/go1.12.10.linux.amd64/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Accept(0xc000190180, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/travis/.gimme/versions/go1.12.10.linux.amd64/src/internal/poll/fd_unix.go:384 +0x1ba
net.(*netFD).accept(0xc000190180, 0xc000051c00, 0x7f59410fad98, 0x0)
	/home/travis/.gimme/versions/go1.12.10.linux.amd64/src/net/fd_unix.go:238 +0x42
net.(*TCPListener).accept(0xc000182038, 0xc000369f60, 0xc000369f68, 0x10)
	/home/travis/.gimme/versions/go1.12.10.linux.amd64/src/net/tcpsock_posix.go:139 +0x32
net.(*TCPListener).Accept(0xc000182038, 0x9e8910, 0xc000180140, 0xc00006fc80, 0x1)
	/home/travis/.gimme/versions/go1.12.10.linux.amd64/src/net/tcpsock.go:260 +0x48
github.com/rumblefrog/source-chat-relay/server/relay.(*Relay).ProcessConnections(0xc000180140)
	/home/travis/gopath/src/github.com/rumblefrog/source-chat-relay/server/relay/relay.go:108 +0xd1
created by github.com/rumblefrog/source-chat-relay/server/relay.(*Relay).Listen
	/home/travis/gopath/src/github.com/rumblefrog/source-chat-relay/server/relay/relay.go:63 +0x16d

goroutine 1240 [runnable]:
github.com/rumblefrog/source-chat-relay/server/relay.(*Relay).ListenClientSend(0xc000180140, 0xc000635320)
	/home/travis/gopath/src/github.com/rumblefrog/source-chat-relay/server/relay/relay.go:163 +0xc9
created by github.com/rumblefrog/source-chat-relay/server/relay.(*Relay).ProcessConnections
	/home/travis/gopath/src/github.com/rumblefrog/source-chat-relay/server/relay/relay.go:130 +0xb7

goroutine 40 [chan receive]:
github.com/rumblefrog/source-chat-relay/server/bot.Listen()
	/home/travis/gopath/src/github.com/rumblefrog/source-chat-relay/server/bot/pipeline.go:12 +0x3f0
created by github.com/rumblefrog/source-chat-relay/server/bot.ready
	/home/travis/gopath/src/github.com/rumblefrog/source-chat-relay/server/bot/bot.go:119 +0x4a

goroutine 5754 [chan receive, 158 minutes]:
github.com/rumblefrog/source-chat-relay/server/relay.(*Relay).ListenClientSend(0xc000180140, 0xc00006e6c0)
	/home/travis/gopath/src/github.com/rumblefrog/source-chat-relay/server/relay/relay.go:163 +0xc9
created by github.com/rumblefrog/source-chat-relay/server/relay.(*Relay).ProcessConnections
	/home/travis/gopath/src/github.com/rumblefrog/source-chat-relay/server/relay/relay.go:130 +0xb7

goroutine 28 [runnable]:
syscall.Syscall(0x3, 0x8, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/travis/.gimme/versions/go1.12.10.linux.amd64/src/syscall/asm_linux_amd64.s:18 +0x5
syscall.Close(0x8, 0x50, 0xc0000a6ed0)
	/home/travis/.gimme/versions/go1.12.10.linux.amd64/src/syscall/zsyscall_linux_amd64.go:310 +0x40
internal/poll.(*FD).destroy(0xc000376100, 0x1, 0x7f5940e8dcd0)
	/home/travis/.gimme/versions/go1.12.10.linux.amd64/src/internal/poll/fd_unix.go:78 +0x44
internal/poll.(*FD).decref(0xc000376100, 0x40c101, 0x50)
	/home/travis/.gimme/versions/go1.12.10.linux.amd64/src/internal/poll/fd_mutex.go:213 +0x42
internal/poll.(*FD).Close(0xc000376100, 0xc000376100, 0x0)
	/home/travis/.gimme/versions/go1.12.10.linux.amd64/src/internal/poll/fd_unix.go:100 +0x50
net.(*netFD).Close(0xc000376100, 0x0, 0xc0000a6f90)
	/home/travis/.gimme/versions/go1.12.10.linux.amd64/src/net/fd_unix.go:184 +0x4f
net.(*conn).Close(0xc00000e0d0, 0x0, 0x0)
	/home/travis/.gimme/versions/go1.12.10.linux.amd64/src/net/net.go:201 +0x4b
github.com/rumblefrog/source-chat-relay/server/relay.(*Relay).ListenClientReceive(0xc000180140, 0xc000130a20)
	/home/travis/gopath/src/github.com/rumblefrog/source-chat-relay/server/relay/relay.go:142 +0x11a
created by github.com/rumblefrog/source-chat-relay/server/relay.(*Relay).ProcessConnections
	/home/travis/gopath/src/github.com/rumblefrog/source-chat-relay/server/relay/relay.go:129 +0x88

goroutine 29 [runnable]:
github.com/rumblefrog/source-chat-relay/server/relay.(*Relay).ListenClientSend(0xc000180140, 0xc000130a20)
	/home/travis/gopath/src/github.com/rumblefrog/source-chat-relay/server/relay/relay.go:163 +0xc9
created by github.com/rumblefrog/source-chat-relay/server/relay.(*Relay).ProcessConnections
	/home/travis/gopath/src/github.com/rumblefrog/source-chat-relay/server/relay/relay.go:130 +0xb7

goroutine 5897 [IO wait]:
internal/poll.runtime_pollWait(0x7f5940e8d4a8, 0x72, 0xffffffffffffffff)
	/home/travis/.gimme/versions/go1.12.10.linux.amd64/src/runtime/netpoll.go:182 +0x56
internal/poll.(*pollDesc).wait(0xc0003ee818, 0x72, 0x1100, 0x1104, 0xffffffffffffffff)
	/home/travis/.gimme/versions/go1.12.10.linux.amd64/src/internal/poll/fd_poll_runtime.go:87 +0x9b
internal/poll.(*pollDesc).waitRead(...)
	/home/travis/.gimme/versions/go1.12.10.linux.amd64/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc0003ee800, 0xc000229300, 0x1104, 0x1104, 0x0, 0x0, 0x0)
	/home/travis/.gimme/versions/go1.12.10.linux.amd64/src/internal/poll/fd_unix.go:169 +0x19b
net.(*netFD).Read(0xc0003ee800, 0xc000229300, 0x1104, 0x1104, 0x203000, 0x0, 0x10f7)
	/home/travis/.gimme/versions/go1.12.10.linux.amd64/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc00000e0e0, 0xc000229300, 0x1104, 0x1104, 0x0, 0x0, 0x0)
	/home/travis/.gimme/versions/go1.12.10.linux.amd64/src/net/net.go:177 +0x69
crypto/tls.(*atLeastReader).Read(0xc00029a0e0, 0xc000229300, 0x1104, 0x1104, 0x26, 0xa77340, 0xc0005629e0)
	/home/travis/.gimme/versions/go1.12.10.linux.amd64/src/crypto/tls/conn.go:761 +0x60
bytes.(*Buffer).ReadFrom(0xc00012c958, 0xa771e0, 0xc00029a0e0, 0x409985, 0x9306a0, 0x9a3c60)
	/home/travis/.gimme/versions/go1.12.10.linux.amd64/src/bytes/buffer.go:207 +0xbd
crypto/tls.(*Conn).readFromUntil(0xc00012c700, 0xa77860, 0xc00000e0e0, 0x5, 0xc00000e0e0, 0x9)
	/home/travis/.gimme/versions/go1.12.10.linux.amd64/src/crypto/tls/conn.go:783 +0xf8
crypto/tls.(*Conn).readRecordOrCCS(0xc00012c700, 0x9e9400, 0xc00012c838, 0xc000562d58)
	/home/travis/.gimme/versions/go1.12.10.linux.amd64/src/crypto/tls/conn.go:590 +0x125
crypto/tls.(*Conn).readRecord(...)
	/home/travis/.gimme/versions/go1.12.10.linux.amd64/src/crypto/tls/conn.go:558
crypto/tls.(*Conn).Read(0xc00012c700, 0xc0006b6000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/home/travis/.gimme/versions/go1.12.10.linux.amd64/src/crypto/tls/conn.go:1236 +0x137
bufio.(*Reader).Read(0xc000634cc0, 0xc00035e3b8, 0x9, 0x9, 0x406214, 0xc000634d80, 0xc000562d58)
	/home/travis/.gimme/versions/go1.12.10.linux.amd64/src/bufio/bufio.go:223 +0x23e
io.ReadAtLeast(0xa77060, 0xc000634cc0, 0xc00035e3b8, 0x9, 0x9, 0x9, 0xa77340, 0xc0003e6120, 0xc000062060)
	/home/travis/.gimme/versions/go1.12.10.linux.amd64/src/io/io.go:310 +0x88
io.ReadFull(...)
	/home/travis/.gimme/versions/go1.12.10.linux.amd64/src/io/io.go:329
net/http.http2readFrameHeader(0xc00035e3b8, 0x9, 0x9, 0xa77060, 0xc000634cc0, 0x0, 0x0, 0xc0004fe180, 0x0)
	/home/travis/.gimme/versions/go1.12.10.linux.amd64/src/net/http/h2_bundle.go:1476 +0x88
net/http.(*http2Framer).ReadFrame(0xc00035e380, 0xc0004fe180, 0x0, 0x0, 0x0)
	/home/travis/.gimme/versions/go1.12.10.linux.amd64/src/net/http/h2_bundle.go:1734 +0xa1
net/http.(*http2clientConnReadLoop).run(0xc000562fb8, 0x9e8e10, 0xc000145fb8)
	/home/travis/.gimme/versions/go1.12.10.linux.amd64/src/net/http/h2_bundle.go:8132 +0x8f
net/http.(*http2ClientConn).readLoop(0xc0001a3c80)
	/home/travis/.gimme/versions/go1.12.10.linux.amd64/src/net/http/h2_bundle.go:8060 +0x76
created by net/http.(*http2Transport).newClientConn
	/home/travis/.gimme/versions/go1.12.10.linux.amd64/src/net/http/h2_bundle.go:7123 +0x637

goroutine 4591 [runnable]:
syscall.Syscall(0x3, 0xc, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/travis/.gimme/versions/go1.12.10.linux.amd64/src/syscall/asm_linux_amd64.s:18 +0x5
syscall.Close(0xc, 0xc000667b01, 0xc000506ec0)
	/home/travis/.gimme/versions/go1.12.10.linux.amd64/src/syscall/zsyscall_linux_amd64.go:310 +0x40
internal/poll.(*FD).destroy(0xc000344780, 0x1, 0x7f5940e8d990)
	/home/travis/.gimme/versions/go1.12.10.linux.amd64/src/internal/poll/fd_unix.go:78 +0x44
internal/poll.(*FD).decref(0xc000344780, 0x1, 0x0)
	/home/travis/.gimme/versions/go1.12.10.linux.amd64/src/internal/poll/fd_mutex.go:213 +0x42
internal/poll.(*FD).Close(0xc000344780, 0xc000344780, 0x0)
	/home/travis/.gimme/versions/go1.12.10.linux.amd64/src/internal/poll/fd_unix.go:100 +0x50
net.(*netFD).Close(0xc000344780, 0xc00007ad80, 0xa88f38)
	/home/travis/.gimme/versions/go1.12.10.linux.amd64/src/net/fd_unix.go:184 +0x4f
net.(*conn).Close(0xc0001ae648, 0x0, 0x0)
	/home/travis/.gimme/versions/go1.12.10.linux.amd64/src/net/net.go:201 +0x4b
github.com/rumblefrog/source-chat-relay/server/relay.(*Relay).ListenClientSend(0xc000180140, 0xc000583c80)
	/home/travis/gopath/src/github.com/rumblefrog/source-chat-relay/server/relay/relay.go:166 +0xe4
created by github.com/rumblefrog/source-chat-relay/server/relay.(*Relay).ProcessConnections
	/home/travis/gopath/src/github.com/rumblefrog/source-chat-relay/server/relay/relay.go:130 +0xb7

goroutine 5753 [runnable]:
syscall.Syscall(0x0, 0xe, 0xc000206c00, 0x400, 0x0, 0x400, 0x0)
	/home/travis/.gimme/versions/go1.12.10.linux.amd64/src/syscall/asm_linux_amd64.s:18 +0x5
syscall.read(0xe, 0xc000206c00, 0x400, 0x400, 0x0, 0xa78a80, 0xdfa410)
	/home/travis/.gimme/versions/go1.12.10.linux.amd64/src/syscall/zsyscall_linux_amd64.go:732 +0x5a
syscall.Read(...)
	/home/travis/.gimme/versions/go1.12.10.linux.amd64/src/syscall/syscall_unix.go:172
internal/poll.(*FD).Read(0xc000460b00, 0xc000206c00, 0x400, 0x400, 0x0, 0x0, 0x0)
	/home/travis/.gimme/versions/go1.12.10.linux.amd64/src/internal/poll/fd_unix.go:165 +0x131
net.(*netFD).Read(0xc000460b00, 0xc000206c00, 0x400, 0x400, 0xc000566f70, 0x4419bc, 0x400)
	/home/travis/.gimme/versions/go1.12.10.linux.amd64/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc00000e2d8, 0xc000206c00, 0x400, 0x400, 0x0, 0x0, 0x0)
	/home/travis/.gimme/versions/go1.12.10.linux.amd64/src/net/net.go:177 +0x69
github.com/rumblefrog/source-chat-relay/server/relay.(*Relay).ListenClientReceive(0xc000180140, 0xc00006e6c0)
	/home/travis/gopath/src/github.com/rumblefrog/source-chat-relay/server/relay/relay.go:138 +0x7a
created by github.com/rumblefrog/source-chat-relay/server/relay.(*Relay).ProcessConnections
	/home/travis/gopath/src/github.com/rumblefrog/source-chat-relay/server/relay/relay.go:129 +0x88

goroutine 3078 [runnable]:
github.com/rumblefrog/source-chat-relay/server/relay.(*Relay).ListenClientSend(0xc000180140, 0xc000583320)
	/home/travis/gopath/src/github.com/rumblefrog/source-chat-relay/server/relay/relay.go:163 +0xc9
created by github.com/rumblefrog/source-chat-relay/server/relay.(*Relay).ProcessConnections
	/home/travis/gopath/src/github.com/rumblefrog/source-chat-relay/server/relay/relay.go:130 +0xb7

goroutine 5856 [select, 2 minutes]:
github.com/bwmarrin/discordgo.(*Session).heartbeat(0xc0001be120, 0xc0000ae580, 0xc0005eb020, 0xa122)
	/home/travis/gopath/src/github.com/bwmarrin/discordgo/wsapi.go:316 +0x382
created by github.com/bwmarrin/discordgo.(*Session).Open
	/home/travis/gopath/src/github.com/bwmarrin/discordgo/wsapi.go:202 +0xb2a

goroutine 5905 [IO wait]:
internal/poll.runtime_pollWait(0x7f5940e8d578, 0x72, 0xffffffffffffffff)
	/home/travis/.gimme/versions/go1.12.10.linux.amd64/src/runtime/netpoll.go:182 +0x56
internal/poll.(*pollDesc).wait(0xc0001a8818, 0x72, 0x1000, 0x10f3, 0xffffffffffffffff)
	/home/travis/.gimme/versions/go1.12.10.linux.amd64/src/internal/poll/fd_poll_runtime.go:87 +0x9b
internal/poll.(*pollDesc).waitRead(...)
	/home/travis/.gimme/versions/go1.12.10.linux.amd64/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc0001a8800, 0xc00022a600, 0x10f3, 0x10f3, 0x0, 0x0, 0x0)
	/home/travis/.gimme/versions/go1.12.10.linux.amd64/src/internal/poll/fd_unix.go:169 +0x19b
net.(*netFD).Read(0xc0001a8800, 0xc00022a600, 0x10f3, 0x10f3, 0x203000, 0x0, 0x5ceae2)
	/home/travis/.gimme/versions/go1.12.10.linux.amd64/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc000182020, 0xc00022a600, 0x10f3, 0x10f3, 0x0, 0x0, 0x0)
	/home/travis/.gimme/versions/go1.12.10.linux.amd64/src/net/net.go:177 +0x69
crypto/tls.(*atLeastReader).Read(0xc0003ba3c0, 0xc00022a600, 0x10f3, 0x10f3, 0x198, 0x200, 0xc000527a10)
	/home/travis/.gimme/versions/go1.12.10.linux.amd64/src/crypto/tls/conn.go:761 +0x60
bytes.(*Buffer).ReadFrom(0xc00012d758, 0xa771e0, 0xc0003ba3c0, 0x409985, 0x9306a0, 0x9a3c60)
	/home/travis/.gimme/versions/go1.12.10.linux.amd64/src/bytes/buffer.go:207 +0xbd
crypto/tls.(*Conn).readFromUntil(0xc00012d500, 0xa77860, 0xc000182020, 0x5, 0xc000182020, 0x29b)
	/home/travis/.gimme/versions/go1.12.10.linux.amd64/src/crypto/tls/conn.go:783 +0xf8
crypto/tls.(*Conn).readRecordOrCCS(0xc00012d500, 0x9e9400, 0xc00012d638, 0xc000078380)
	/home/travis/.gimme/versions/go1.12.10.linux.amd64/src/crypto/tls/conn.go:590 +0x125
crypto/tls.(*Conn).readRecord(...)
	/home/travis/.gimme/versions/go1.12.10.linux.amd64/src/crypto/tls/conn.go:558
crypto/tls.(*Conn).Read(0xc00012d500, 0xc0001b3000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/home/travis/.gimme/versions/go1.12.10.linux.amd64/src/crypto/tls/conn.go:1236 +0x137
bufio.(*Reader).fill(0xc00006fec0)
	/home/travis/.gimme/versions/go1.12.10.linux.amd64/src/bufio/bufio.go:100 +0x10f
bufio.(*Reader).Peek(0xc00006fec0, 0x2, 0xc0002cabf0, 0xe, 0xc0003a0a01, 0x43548f, 0xc000527d28)
	/home/travis/.gimme/versions/go1.12.10.linux.amd64/src/bufio/bufio.go:138 +0x4f
github.com/gorilla/websocket.(*Conn).read(0xc0000ae580, 0x2, 0xc000527db8, 0x42b631, 0x9e94a8, 0xc000527dc8, 0x42ad8f)
	/home/travis/gopath/src/github.com/gorilla/websocket/conn.go:370 +0x40
github.com/gorilla/websocket.(*Conn).advanceFrame(0xc0000ae580, 0x0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/gorilla/websocket/conn.go:798 +0x5c
github.com/gorilla/websocket.(*Conn).NextReader(0xc0000ae580, 0xe577e0, 0x200, 0xc000182078, 0x0, 0x0)
	/home/travis/gopath/src/github.com/gorilla/websocket/conn.go:980 +0xa0
github.com/gorilla/websocket.(*Conn).ReadMessage(0xc0000ae580, 0x1, 0xc00040a600, 0x297, 0x600, 0xc000180460, 0x0)
	/home/travis/gopath/src/github.com/gorilla/websocket/conn.go:1064 +0x2f
github.com/bwmarrin/discordgo.(*Session).listen(0xc0001be120, 0xc0000ae580, 0xc0005eb020)
	/home/travis/gopath/src/github.com/bwmarrin/discordgo/wsapi.go:217 +0x8e
created by github.com/bwmarrin/discordgo.(*Session).Open
	/home/travis/gopath/src/github.com/bwmarrin/discordgo/wsapi.go:203 +0xb67
`

**Comment by rumblefrog** [comment]
Should be addressed in v2.1.1

**Comment by uGamers** [comment]
With the new release the bot seems broken nothing writes to discord anymore.

Did you test this or is it just me?

**Comment by rumblefrog** [comment]
Shouldn't be the case, I don't see anything affecting it, I'll check it out.

**Comment by rumblefrog** [comment]
Apologies, this commit should fix it https://github.com/rumblefrog/source-chat-relay/commit/11eb7ecff84948c377adb2a57d718eaaad4e6e57 it will be available in v2.1.2
